<a href="https://colab.research.google.com/github/Pavitrapanya/Sentiment-Analysis-of-Twitter-and-Reddit-Comments/blob/main/Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DATA INGESTION**

In [ ]:

import numpy as np
import pandas as pd
df2=pd.read_csv('/content/Reddit_Data.csv')
df1=pd.read_csv('/content/Twitter_Data.csv')
df=pd.concat([df2,df1])
len(df)


200229

**DATA PREPROCESSING**

In [ ]:
df.head()

clean_comment  category
0   family mormon have never tried explain them t...       1.0
1  buddhism has very much lot compatible with chr...       1.0
2  seriously don say thing first all they won get...      -1.0
3  what you have learned yours and only yours wha...       0.0
4  for your own benefit you may want read living ...       1.0

In [ ]:
df['clean_comment'].dtype

dtype('O')

In [ ]:
df = df.dropna()
df.isna().sum()

clean_comment    0
category         0
dtype: int64

In [ ]:
df['clean_comment'].dtype

dtype('O')

In [ ]:
df['clean_comment']=df['clean_comment'].str.lower()

In [ ]:
import string
punc=string.punctuation
print(punc)
def remove_punc(text):
  str(text)
  for ch in punc:
    text=text.replace(ch,' ')
  return text

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [ ]:
d=df['clean_comment']
d.head()
d=d.astype(str)
d=d.apply(remove_punc)

In [ ]:
df['clean_comment']=d

In [ ]:
df.head()

clean_comment  category
0   family mormon have never tried explain them t...       1.0
1  buddhism has very much lot compatible with chr...       1.0
2  seriously don say thing first all they won get...      -1.0
3  what you have learned yours and only yours wha...       0.0
4  for your own benefit you may want read living ...       1.0

In [ ]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [ ]:
'''wn = nltk.WordNetLemmatizer()
from nltk.corpus import stopwords
stopWords = stopwords.words('english')
def clean(text):
  text = re.sub(r"[^A-Za-z0-9]",' ', text)
  text = [wn.lemmatize(word) for word in text.split(' ') if ((word not in stopWords) & len(word)!=0)]
  return "".join(text)'''
import re
def wordopt(text):
   text = re.sub(r"[^a-zA-Z]", " ", text)
   text = text.split()
   text = ' '.join(text)
   return text

In [ ]:
d=d.astype(str)
d=d.apply(wordopt) 
d.head()
df['clean_comment']=d
len(df)
df['clean_comment']

0         family mormon have never tried explain them th...
1         buddhism has very much lot compatible with chr...
2         seriously don say thing first all they won get...
3         what you have learned yours and only yours wha...
4         for your own benefit you may want read living ...
                                ...                        
162975    why these crores paid neerav modi not recovere...
162976    dear rss terrorist payal gawar what about modi...
162977    did you cover her interaction forum where she ...
162978    there big project came into india modi dream p...
162979    have you ever listen about like gurukul where ...
Name: clean_comment, Length: 200118, dtype: object

In [ ]:
from nltk.stem import WordNetLemmatizer
# from nltk.tokenize import TweetTokenizer 

lemmatizer = WordNetLemmatizer() 
def lemma(text):  
    lemmas = [lemmatizer.lemmatize(word, pos ='v') for word in text] 
    text = ''.join(lemmas)    
    return text

In [ ]:
d=d.astype(str)
d=d.apply(lemma) 
d.head()
df['clean_comment']=d
df['clean_comment']

0         family mormon have never tried explain them th...
1         buddhism has very much lot compatible with chr...
2         seriously don say thing first all they won get...
3         what you have learned yours and only yours wha...
4         for your own benefit you may want read living ...
                                ...                        
162975    why these crores paid neerav modi not recovere...
162976    dear rss terrorist payal gawar what about modi...
162977    did you cover her interaction forum where she ...
162978    there big project came into india modi dream p...
162979    have you ever listen about like gurukul where ...
Name: clean_comment, Length: 200118, dtype: object

**BUILDING MODEL USING MULTINOMIAL NB**

In [ ]:
df['category'].value_counts()

 1.0    88079
 0.0    68253
-1.0    43786
Name: category, dtype: int64

In [ ]:
x=df['clean_comment'].values
y=df['category'].values

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [ ]:
x_train.shape

(150088,)

In [ ]:
x_test.shape

(50030,)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english')

In [ ]:
x_train_vect=cv.fit_transform(x_train)   
x_test_vect=cv.transform(x_test)

In [ ]:
x_train


array(['modi says his govt has shown courage for surgical strike all spheres land sky and space again',
       'welfare exserviceman priority modi govt then direction from govt should given all psu banks keep them their native place after reemployment defence personal always away from home while defence reemployed after discharged from service jai hind',
       'the numbers may not lying actually india slightly more peaceful but not owe our leaders what actually brought upon the change narendra modi biggest grouse was that felt that media was unusually harsh him for murderous hindu mobs guided congress politicians roamed the streets delhi slaughtering sikhs and most the main accused never faced justice same goes for bombay riots shiv sena goons rioted with impunity and the chief accused managed scot free same goes for bhagalpur and many other instances communal riots what actually changed from the ubiquitous television camera ground reporting media yes the same msm which few never tire

In [ ]:
from sklearn.naive_bayes import MultinomialNB


In [ ]:
nb=MultinomialNB()
nb

MultinomialNB()

In [ ]:
nb.fit(x_train_vect,y_train)

MultinomialNB()

In [ ]:
y_pred=nb.predict(x_test_vect)

In [ ]:
y_pred

array([0., 1., 1., ..., 0., 1., 1.])

In [ ]:
y_test

array([ 0.,  1.,  1., ...,  0.,  0., -1.])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.7000399760143914

In [ ]:
confusion_matrix(y_test,y_pred)

array([[ 5992,   711,  4331],
       [  844,  9534,  6541],
       [ 1274,  1306, 19497]])